import {mkdir} from 'node:fs/promises';
await mkdir('artifacts',{recursive:true});
import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1100}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
await page.goto('http://127.0.0.1:5173');await page.screenshot({path:'artifacts/desktop-check.png',fullPage:true});
for(const route of ['courses','grades','attendance','assessments','planner','timetable','ideas','portfolio','settings']){await page.locator(`nav a[href="#${route}"]`).click();await page.waitForTimeout(30);assert(await page.locator('h1').count());}
await page.locator('nav a[href="#grades"]').click();await page.locator('.grade-input').nth(0).selectOption('O');await page.locator('.grade-input').nth(1).selectOption('A+');assert.match(await page.locator('.stat-card').nth(0).textContent(),/9.79/);
await page.getByRole('button',{name:'What-if mode',exact:true}).click();await page.locator('.grade-input').nth(0).selectOption('F');assert.match(await page.locator('.stat-card').nth(0).textContent(),/4.07/);await page.getByRole('button',{name:'Recorded grades',exact:true}).click();assert.match(await page.locator('.stat-card').nth(0).textContent(),/9.79/);
await page.locator('nav a[href="#attendance"]').click();await page.locator('[data-action="edit-attendance"]').first().click();await page.locator('input[name="attended"]').fill('14');await page.locator('input[name="held"]').fill('20');await page.getByRole('button',{name:'Save changes',exact:true}).click();assert.match(await page.locator('.att-advice').first().textContent(),/next 4/);
await page.locator('nav a[href="#assessments"]').click();await page.locator('.score-input').first().fill('8');await page.locator('.score-input').first().blur();assert.match(await page.locator('.stat-card').first().textContent(),/8.0/);
await page.locator('nav a[href="#ideas"]').click();await page.getByRole('button',{name:'Plant an idea'}).click();await page.locator('[name="title"]').fill('FIH project idea');await page.locator('[name="body"]').fill('Document a local heritage site.');await page.getByRole('button',{name:'Save changes',exact:true}).click();assert.equal(await page.locator('.idea-card').count(),1);await page.locator('.idea-status').selectOption('Growing');assert.match(await page.locator('.idea-column').nth(1).textContent(),/FIH project/);
await page.locator('nav a[href="#portfolio"]').click();await page.getByRole('button',{name:'Edit profile',exact:true}).click();await page.locator('[name="name"]').fill('Test Student');await page.locator('[name="skills"]').fill('Python, Mathematics');await page.getByRole('button',{name:'Save changes',exact:true}).click();assert.match(await page.locator('.portfolio-hero').textContent(),/Test Student/);
await page.getByRole('button',{name:'Add project',exact:false}).click();await page.locator('[name="title"]').fill('Private test project');await page.getByRole('button',{name:'Save changes',exact:true}).click();const dlPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Export portfolio',exact:false}).click();const dl=await dlPromise;const fs=await import('node:fs/promises');const html=await fs.readFile(await dl.path(),'utf8');assert(!html.includes('Private test project'));assert(!html.includes('9.79'));assert(html.includes('Test Student'));
await page.reload();assert.match(await page.locator('.portfolio-hero').textContent(),/Test Student/);
await page.locator('nav a[href="#courses"]').click();await page.getByRole('button',{name:'Add course',exact:false}).click();await page.locator('[name="name"]').fill('Future Course');await page.locator('[name="code"]').fill('TEST201');await page.locator('[name="semester"]').fill('2');await page.getByRole('button',{name:'Save changes',exact:true}).click();await page.locator('#semester').selectOption('2');assert.equal(await page.locator('.course-card').count(),1);
await page.locator('nav a[href="#planner"]').click();await page.locator('#plan-target').fill('10');await page.locator('#plan-future').fill('1');assert.match(await page.locator('#plan-result').textContent(),/not reachable/);
await page.locator('nav a[href="#settings"]').click();const backupWait=page.waitForEvent('download');await page.getByRole('button',{name:'Export full backup'}).click();const backup=await backupWait;const path=await backup.path();const saved=JSON.parse(await fs.readFile(path,'utf8'));assert.equal(saved.profile.name,'Test Student');await page.locator('#import-file').setInputFiles(path);await page.waitForTimeout(200);assert.equal(await page.locator('h1').textContent(),'Make this space yours.');
await page.evaluate(()=>localStorage.clear());await page.reload();await page.locator('nav a[href="#overview"]').click();await page.screenshot({path:'artifacts/desktop-check.png',fullPage:true});
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'artifacts/mobile-check.png',fullPage:true});
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
for(const route of ['courses','grades','attendance','assessments','planner','timetable','ideas','portfolio','settings']){await page.goto(`http://127.0.0.1:5173/#${route}`);await page.waitForTimeout(30);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`Overflow on ${route}`);}
assert.deepEqual(errors,[]);console.log('PASS: 10 routes; grade/scenario math; attendance; marks; ideas; profile; private project export filtering; browser persistence; add course/semester; goal planner; backup/import; mobile overflow.');await browser.close();
