import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {readFile,mkdir} from 'node:fs/promises';
await mkdir('artifacts',{recursive:true});
const b=await chromium.launch();const p=await b.newPage({viewport:{width:1440,height:1000}});const errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());
await p.goto('http://127.0.0.1:5173/');assert.equal(await p.locator('.workspace-shortcuts').count(),1);assert.match(await p.locator('.workspace-shortcuts').textContent(),/SGPA & CGPA calculator/);
await p.locator('nav a[href="#notes"]').click();await p.getByRole('button',{name:'New note',exact:false}).click();await p.locator('#note-title').fill('My private math notes');await p.locator('#note-body').fill('PRIVATE NOTE DO NOT PUBLISH\nSome lecture ideas. <script>alert(1)</script>');await p.locator('#note-category').selectOption('Lecture');await p.locator('#note-course').selectOption({index:1});await p.reload();assert.equal(await p.locator('#note-title').inputValue(),'My private math notes');assert.match(await p.locator('#note-body').inputValue(),/PRIVATE NOTE/);
await p.getByRole('button',{name:'Pin',exact:true}).click();assert.match(await p.locator('.note-list-item').first().textContent(),/PINNED/);
await p.locator('#note-search').fill('not a match');assert.equal(await p.locator('.note-list-item').count(),0);await p.locator('#note-search').fill('math');assert.equal(await p.locator('.note-list-item').count(),1);
const noteDownload=p.waitForEvent('download');await p.getByRole('button',{name:'Download note',exact:true}).click();assert.match(await readFile(await (await noteDownload).path(),'utf8'),/PRIVATE NOTE/);
await p.locator('nav a[href="#projects"]').click();await p.waitForSelector('.project-dashboard-card');assert.equal(await p.locator('.project-dashboard-card').count(),3);await p.locator('.project-status-input').first().selectOption('In progress');await p.getByRole('button',{name:'Add milestone to CivicEye'}).click();await p.locator('[name="title"]').fill('PRIVATE MILESTONE');await p.getByRole('button',{name:'Save changes',exact:true}).click();await p.getByRole('button',{name:'Complete PRIVATE MILESTONE',exact:true}).click();assert.match(await p.locator('.stat-card').nth(2).textContent(),/1/);
await p.locator('.project-dashboard-card').first().getByRole('button',{name:'Add a project note'}).click();await p.locator('#note-title').fill('CivicEye thinking');await p.locator('#note-body').fill('PRIVATE PROJECT NOTE');assert.equal(await p.locator('#note-project').inputValue(),'civiceye');
await p.locator('nav a[href="#portfolio"]').click();const pd=p.waitForEvent('download');await p.getByRole('button',{name:'Export portfolio',exact:false}).click();const ph=await readFile(await(await pd).path(),'utf8');assert(!ph.includes('PRIVATE'));assert(ph.includes('CivicEye'));
await p.locator('nav a[href="#settings"]').click();const bd=p.waitForEvent('download');await p.getByRole('button',{name:'Export full backup'}).click();const path=await(await bd).path();const json=JSON.parse(await readFile(path,'utf8'));assert.equal(json.notes.length,2);assert(json.projects[0].milestones[0].done);await p.locator('#import-file').setInputFiles(path);await p.waitForTimeout(100);await p.locator('nav a[href="#notes"]').click();await p.waitForSelector('.note-list-item');assert.equal(await p.locator('.note-list-item').count(),2);
await p.goto('http://127.0.0.1:5173/portfolio/');assert.match(await p.locator('h1').textContent(),/Archit/);assert(!await p.locator('body').textContent().then(t=>t.includes('PRIVATE')));assert.equal(await p.getByRole('link',{name:'College workspace',exact:false}).count(),1);
await p.goto('http://127.0.0.1:5173/#projects');await p.screenshot({path:'artifacts/projects-check.png',fullPage:true});
for(const route of ['notes','projects']){await p.goto('http://127.0.0.1:5173/#'+route);await p.setViewportSize({width:390,height:844});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Overflow on '+route);}
await p.goto('http://127.0.0.1:5174/');await p.setViewportSize({width:1440,height:1000});assert.equal(await p.locator('.member-card').count(),5);assert.equal(await p.locator('.project-card').count(),3);assert.equal(await p.locator('.member-card[href]').count(),1);assert.equal(await p.locator('.member-card.linked').getAttribute('href'),'https://architspace.vercel.app/');assert.equal(await p.getByRole('link',{name:'Visit CivicEye',exact:false}).getAttribute('href'),'https://civiceye.co.in/');
for(const name of ['CivicEye','AgriPulse','MetrikAI']){await p.getByRole('button',{name:'Read about '+name,exact:true}).first().click();assert.equal(await p.locator('#dialog-title').textContent(),name);await p.keyboard.press('Escape');assert(!(await p.locator('dialog').evaluate(d=>d.open)));}
await p.screenshot({path:'artifacts/team-desktop-check.png',fullPage:true});
for(const width of [1100,820,620,390,320]){await p.setViewportSize({width,height:844});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Team overflow at '+width);}
await p.setViewportSize({width:390,height:844});await p.locator('.mobile-toggle').click();assert.equal(await p.locator('.mobile-toggle').getAttribute('aria-expanded'),'true');await p.locator('#main-nav a[href="#people"]').click();assert.equal(await p.locator('.mobile-toggle').getAttribute('aria-expanded'),'false');await p.evaluate(()=>scrollTo(0,0));await p.screenshot({path:'artifacts/team-mobile-check.png',fullPage:true});
await p.route('https://architspace.vercel.app/**',route=>route.fulfill({contentType:'text/html',body:'<h1>Archit destination</h1>'}));await p.locator('.member-card.linked').click();assert.match(p.url(),/^https:\/\/architspace.vercel.app/);
assert.deepEqual(errors,[]);await b.close();console.log('PASS: notes autosave/search/pin/export; project states/milestones/linked notes; backup restore; private-export exclusion; real built workspace and public portfolio; team cards, all project dialogs, links and mobile navigation.');
