import {test} from 'node:test';
import assert from 'node:assert/strict';
import {initial,validate,GRADES,gpa,attendance,assessmentStats,requiredGpa,markGrade} from './core.js';
const c=(credits,grade,extra={})=>({credits,grade,include:true,pf:false,plan:'',...extra});
test('timetable seeds 26 credits; provisional FIH exclusion leaves 24 GPA credits',()=>{const d=initial();assert.equal(d.courses.reduce((s,c)=>s+c.credits,0),26);assert.equal(gpa(d.courses,GRADES).possible,24);assert.equal(d.courses.find(c=>c.code==='23ENG101').credits,3);assert.equal(validate(d),d);});
test('empty and pending grades yield no GPA, not zero',()=>{assert.equal(gpa([],GRADES).value,null);assert.equal(gpa([c(3,'')],GRADES).value,null);assert.equal(gpa([c(3,'W')],GRADES).value,null);});
test('credit weighting and failed grades remain in denominator',()=>{const s=gpa([c(4,'O'),c(3,'A+'),c(3,'F')],GRADES);assert.equal(s.credits,10);assert.equal(s.value,6.85);assert.equal(s.complete,true);});
test('CGPA weights all courses instead of averaging semesters',()=>{assert.equal(gpa([c(4,'O'),c(1,'F')],GRADES).value,8);});
test('pass/fail exclusions and optional inclusion',()=>{assert.equal(gpa([c(3,'O'),c(2,'PASS',{pf:true,include:false})],GRADES).credits,3);assert.equal(gpa([c(2,'PASS',{pf:true,passPoints:5})],GRADES).value,5);});
test('what-if overrides are non-destructive; empty plan falls back',()=>{const courses=[c(3,'F',{plan:'O'}),c(3,'A')];assert.equal(gpa(courses,GRADES,true).value,9.5);assert.equal(gpa(courses,GRADES).value,4.5);});
test('partial coverage excludes blank grade credits',()=>{const s=gpa([c(4,'O'),c(3,'')],GRADES);assert.equal(s.value,10);assert.equal(s.credits,4);assert.equal(s.possible,7);assert.equal(s.complete,false);});
test('attendance boundaries and invalid entries',()=>{assert.deepEqual(attendance(0,0),{pct:null,miss:0,need:0});assert.equal(attendance(15,20).miss,0);assert.equal(attendance(18,20).miss,4);assert.equal(attendance(14,20).need,4);assert.equal(attendance(10,20).need,20);assert.equal(attendance(2,1).error,true);assert.equal(attendance(-1,1).error,true);assert.equal(attendance(1.5,2).error,true);assert.equal(attendance(1,2,100).need,Infinity);});
test('weighted assessment with different raw maximum',()=>{const s=assessmentStats([{max:50,weight:20,score:40},{max:100,weight:80,score:''}],80);assert.equal(s.secured,16);assert.equal(s.required,80);assert.equal(s.valid,true);assert.equal(s.complete,false);});
test('zero mark counts as completed; blank mark stays pending',()=>{const s=assessmentStats([{max:10,weight:10,score:0},{max:90,weight:90,score:''}]);assert.equal(s.done,10);assert.equal(s.remaining,90);assert.equal(s.secured,0);});
test('invalid weights and scores block final marks',()=>{assert.equal(assessmentStats([{max:100,weight:99,score:80}]).valid,false);assert.equal(assessmentStats([{max:10,weight:100,score:11}]).valid,false);assert.equal(assessmentStats([]).valid,false);});
test('target CGPA identifies exact or impossible goals',()=>{const s=gpa([c(20,'B+')],GRADES);assert.equal(requiredGpa(s,9,20),10);assert.equal(requiredGpa(s,9.5,20),11);assert.equal(requiredGpa(s,9,0),null);assert.equal(requiredGpa(gpa([],GRADES),9.5,24),9.5);});
test('custom mark thresholds only; no built-in campus cutoff',()=>{assert.equal(markGrade(90,{}),null);assert.equal(markGrade(90,{O:93,'A+':85,F:0}),'A+');assert.equal(markGrade(93,{O:93,'A+':85,F:0}),'O');});
test('backup rejects invalid schemas and course attendance',()=>{assert.throws(()=>validate({}));const d=initial();d.courses[0].attended=2;assert.throws(()=>validate(d));});

// Personalisation & deployment boundaries
import {ARCHIT_PROFILE,migratePersonalization,normalizeSiteUrl} from './profile.js';
import {publicSnapshot,renderPublicSite} from './public-site.js';
test('Archit is seeded with qualified skills, not invented experience',()=>{const d=initial();assert.equal(d.profile.name,'Archit Renjeev');assert.match(d.profile.bio,/Kerala/);assert.match(d.profile.bio,/Bengaluru/);assert.match(d.profile.skills,/AI model training \(learning\)/);assert.equal(d.profile.experience,'');});
test('migration preserves grades, user profile edits and projects',()=>{const d=initial();delete d.profileRevision;delete d.site;d.profile={...ARCHIT_PROFILE,name:'',headline:'AI & Data Science student',bio:'My custom bio'};d.courses[0].grade='O';d.projects=[{id:'project',title:'Existing project'}];migratePersonalization(d);assert.equal(d.profile.name,'Archit Renjeev');assert.equal(d.profile.bio,'My custom bio');assert.equal(d.courses[0].grade,'O');assert.equal(d.projects.length,1);d.profile.name='';migratePersonalization(d);assert.equal(d.profile.name,'');});
test('public export allowlists fields and excludes private records',()=>{const d=initial();d.courses[0].notes='SECRET CLASS NOTE';d.profile.privateSecret='PRIVATE PROFILE KEY';d.projects=[{id:'private',title:'SECRET PROJECT',public:false},{id:'public',title:'Visible project',public:true,description:'Public description',tech:'Web',url:'https://example.com',privateNotes:'DO NOT EXPORT'}];const snapshot=publicSnapshot(d),text=JSON.stringify(snapshot);for(const secret of ['SECRET','PRIVATE','DO NOT EXPORT','courses','attendance'])assert(!text.includes(secret));assert.equal(snapshot.projects.length,1);assert.equal(snapshot.format,'archispace-public-v1');});
test('site URL accepts HTTPS domains, rejects invalid deployment addresses',()=>{assert.equal(normalizeSiteUrl('archit.example.com'),'https://archit.example.com');assert.equal(normalizeSiteUrl(''),'');for(const u of ['javascript:alert(1)','http://example.com','https://example.com/path','https://user:pass@example.com','https://example.com/?q=1'])assert.throws(()=>normalizeSiteUrl(u));});
test('portfolio metadata is escaped; no scripts or hidden private data',()=>{const d=initial();d.site.title='<script>alert(1)</script>';d.site.url='https://example.com';d.profile.bio='<img src=x onerror=alert(1)>';const h=renderPublicSite(d);assert(h.includes('&lt;script&gt;'));assert(!h.includes('<script>'));assert(h.includes('rel="canonical" href="https://example.com/"'));assert(!h.includes('verdant.personal.v1'));});
test('ArchiSpace migration preserves previous academic and personalised data',()=>{const d=initial();delete d.brandRevision;d.site.title='Archit Renjeev';d.courses[0].grade='A+';d.courses[0].notes='Keep my notes';migratePersonalization(d);assert.equal(d.site.title,'ArchiSpace · Archit Renjeev');assert.equal(d.courses[0].grade,'A+');assert.equal(d.courses[0].notes,'Keep my notes');delete d.brandRevision;d.site.title='My custom title';migratePersonalization(d);assert.equal(d.site.title,'My custom title');});
test('public exports carry ArchiSpace branding while retaining owner identity',()=>{const html=renderPublicSite(initial());assert(html.includes('ArchiSpace<span>'));assert(html.includes('<h1>Archit Renjeev</h1>'));assert(!html.includes('Verdant'));});

import {migrateWorkspace} from './projects.js';
test('older workspaces gain notes and known projects without losing data',()=>{const d=initial();delete d.toolsRevision;delete d.notes;d.projects=[{id:'old-civic',title:'CivicEye',description:'My edited project',tech:'',url:'',public:false}];d.courses[0].grade='O';migrateWorkspace(d);assert.deepEqual(d.notes,[]);assert.equal(d.projects.length,3);assert.equal(d.projects[0].description,'My edited project');assert.equal(d.projects[0].public,false);assert.equal(d.courses[0].grade,'O');migrateWorkspace(d);assert.equal(d.projects.length,3);assert.equal(validate(d),d);});
test('notebook and project workflow round-trip through full backup validation',()=>{const d=initial();d.notes=[{id:'note1',title:'Math',body:'Private content',category:'Lecture',course:d.courses[0].id,projectId:'',updated:new Date().toISOString(),pinned:true}];d.projects[0].milestones=[{id:'m1',title:'Private milestone',done:false}];d.projects[0].nextStep='Private action';const restored=validate(JSON.parse(JSON.stringify(d)));assert.equal(restored.notes[0].body,'Private content');assert.equal(restored.projects[0].milestones.length,1);const publicText=JSON.stringify(publicSnapshot(d));for(const privateText of ['Private content','Private milestone','Private action','milestones','nextStep'])assert(!publicText.includes(privateText));});
test('invalid notebook and workflow entries are rejected',()=>{const d=initial();d.notes=[{id:'x',title:'Broken'}];assert.throws(()=>validate(d));d.notes=[];d.projects[0].status='Made up status';assert.throws(()=>validate(d));});
test('seeded project progress is unknown rather than invented',()=>{const d=initial();assert.deepEqual(d.projects.map(p=>p.title),['CivicEye','AgriPulse','MetrikAI']);assert(d.projects.every(p=>p.status==='Not set'&&p.milestones.length===0));assert.equal(d.projects[0].url,'https://civiceye.co.in');});

import {normalizeProjects,readProjectFile,portableProjects} from './project-schema.js';
import {mergePublicStories,publicProjectStories} from './projects.js';
test('bio expands interests and preserves startup as an aspiration',()=>{const d=initial();for(const term of ['gaming','automotive','Iron Man','cars and bikes','learning AI model training','hope to build a startup'])assert(d.profile.bio.includes(term));assert(d.profile.aspiration.includes('One day'));});
test('profile revision adds interests without overwriting a custom or deliberately empty bio',()=>{for(const bio of ['My own writing','']){const d=initial();d.profileRevision=1;d.profile.bio=bio;delete d.profile.interests;delete d.profile.aspiration;migratePersonalization(d);assert.equal(d.profile.bio,bio);assert(d.profile.interests.includes('Iron Man'));assert.equal(d.profileRevision,2);}});
test('project defaults reflect supplied flagship and event facts, never invented solutions or lessons',()=>{const d=initial();assert.equal(d.projects.filter(p=>p.flagship).length,1);assert.equal(d.projects[0].title,'CivicEye');assert.equal(d.projects[1].eventVenue,'IITM Delhi');assert.match(d.projects[1].eventOutcome,/Shortlisted.*narrowly missed/);assert.equal(d.projects[2].eventType,'National hackathon');for(const p of d.projects){assert.equal(p.problemStatement,'');assert.equal(p.idealSolution,'');assert.equal(p.lessonsLearned,'');}});
test('story migration updates only untouched descriptions and preserves private work',()=>{const d=initial();delete d.projectStoryRevision;d.projects[0].description='Our passion project with 404 Error Found.';d.projects[1].description='My custom AgriPulse story';d.projects[1].eventOutcome='';d.projects[0].nextStep='Private next step';migrateWorkspace(d);assert.match(d.projects[0].description,/flagship/);assert.equal(d.projects[1].description,'My custom AgriPulse story');assert.equal(d.projects[1].eventOutcome,'');assert.equal(d.projects[0].nextStep,'Private next step');assert.equal(d.projects[0].problemStatement,'');});
test('public stories survive backup and public export, excluding workflow and notes',()=>{const d=initial();d.projects[0].problemStatement='A real problem';d.projects[0].idealSolution='Our ideal solution';d.projects[0].lessonsLearned='An honest reflection';d.projects[0].nextStep='PRIVATE STEP';d.projects[0].milestones=[{id:'m',title:'PRIVATE MILESTONE',done:false}];assert.equal(validate(JSON.parse(JSON.stringify(d))).projects[0].lessonsLearned,'An honest reflection');const publicData=publicSnapshot(d);assert.equal(publicData.projects[0].problemStatement,'A real problem');assert(!JSON.stringify(publicData).includes('PRIVATE'));assert(!JSON.stringify(portableProjects(publicProjectStories(d.projects))).includes('PRIVATE'));});
test('cross-site import merges by stable ID while preserving private fields and visibility',()=>{const d=initial();d.projects[0].public=false;d.projects[0].nextStep='Secret task';d.projects[0].status='On hold';d.projects[0].milestones=[{id:'m',title:'Secret',done:false}];const p=normalizeProjects([{...d.projects[0],name:'CivicEye renamed',description:'New story',lessonsLearned:'Lesson'}]);mergePublicStories(d,p);assert.equal(d.projects[0].title,'CivicEye renamed');assert.equal(d.projects[0].public,false);assert.equal(d.projects[0].nextStep,'Secret task');assert.equal(d.projects[0].status,'On hold');assert.equal(d.projects[0].milestones.length,1);assert.equal(d.projects[0].lessonsLearned,'Lesson');assert.equal(d.projects.length,3);});
test('portable project validation rejects private backups, duplicates, dangerous links and multiple flagships',()=>{assert.throws(()=>readProjectFile(initial()),/Private workspace backups/);assert.throws(()=>normalizeProjects([{id:'x',name:'X'},{id:'x',name:'Y'}]),/Duplicate/);assert.throws(()=>normalizeProjects([{id:'x',name:'X',url:'javascript:alert(1)'}]),/HTTP/);assert.throws(()=>normalizeProjects([{id:'x',name:'X',flagship:true},{id:'y',name:'Y',flagship:true}]),/one flagship/);assert.throws(()=>normalizeProjects([{id:'x',name:''}]),/name/);assert.throws(()=>normalizeProjects([{id:'" onclick="x',name:'X'}]),/IDs/);});
test('schema accepts legacy team copy, public snapshot, and portable round-trip',()=>{const legacy=readProjectFile({networkName:'404ErrorNetwork',projects:[{id:'x',name:'X',detail:'Original details',summary:'Old teaser'}]});assert.equal(legacy[0].description,'Original details');const d=initial();const current=readProjectFile(publicSnapshot(d));assert.equal(current[0].name,'CivicEye');assert.deepEqual(readProjectFile(portableProjects(current)),current);});
test('new story fields validate types and escape public HTML',()=>{const d=initial();d.projects[0].lessonsLearned='<script>alert(1)</script>';assert(renderPublicSite(publicSnapshot(d)).includes('&lt;script&gt;alert(1)&lt;/script&gt;'));d.projects[0].eventType=[];assert.throws(()=>validate(d),/story/);d.projects[0].eventType='National hackathon';d.projects[0].flagship='yes';assert.throws(()=>validate(d),/flagship/);});
